# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mcp_pb2 as mcp__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MCPServiceStub(object):
    """The Model/DB Control Plane service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveDocument = channel.unary_unary(
                '/mcp.MCPService/SaveDocument',
                request_serializer=mcp__pb2.SaveDocumentRequest.SerializeToString,
                response_deserializer=mcp__pb2.SaveDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/mcp.MCPService/GetDocument',
                request_serializer=mcp__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=mcp__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.WriteMetric = channel.unary_unary(
                '/mcp.MCPService/WriteMetric',
                request_serializer=mcp__pb2.WriteMetricRequest.SerializeToString,
                response_deserializer=mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.WriteAudit = channel.unary_unary(
                '/mcp.MCPService/WriteAudit',
                request_serializer=mcp__pb2.WriteAuditRequest.SerializeToString,
                response_deserializer=mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.QueryLLM = channel.unary_unary(
                '/mcp.MCPService/QueryLLM',
                request_serializer=mcp__pb2.QueryLLMRequest.SerializeToString,
                response_deserializer=mcp__pb2.QueryLLMResponse.FromString,
                _registered_method=True)


class MCPServiceServicer(object):
    """The Model/DB Control Plane service definition.
    """

    def SaveDocument(self, request, context):
        """Saves document metadata to the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Retrieves document metadata from the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteMetric(self, request, context):
        """Writes a metric event to the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteAudit(self, request, context):
        """Writes an audit event to the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLLM(self, request, context):
        """Queries the LLM (stub).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveDocument,
                    request_deserializer=mcp__pb2.SaveDocumentRequest.FromString,
                    response_serializer=mcp__pb2.SaveDocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=mcp__pb2.GetDocumentRequest.FromString,
                    response_serializer=mcp__pb2.GetDocumentResponse.SerializeToString,
            ),
            'WriteMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteMetric,
                    request_deserializer=mcp__pb2.WriteMetricRequest.FromString,
                    response_serializer=mcp__pb2.StatusResponse.SerializeToString,
            ),
            'WriteAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteAudit,
                    request_deserializer=mcp__pb2.WriteAuditRequest.FromString,
                    response_serializer=mcp__pb2.StatusResponse.SerializeToString,
            ),
            'QueryLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLLM,
                    request_deserializer=mcp__pb2.QueryLLMRequest.FromString,
                    response_serializer=mcp__pb2.QueryLLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.MCPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.MCPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCPService(object):
    """The Model/DB Control Plane service definition.
    """

    @staticmethod
    def SaveDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCPService/SaveDocument',
            mcp__pb2.SaveDocumentRequest.SerializeToString,
            mcp__pb2.SaveDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCPService/GetDocument',
            mcp__pb2.GetDocumentRequest.SerializeToString,
            mcp__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCPService/WriteMetric',
            mcp__pb2.WriteMetricRequest.SerializeToString,
            mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCPService/WriteAudit',
            mcp__pb2.WriteAuditRequest.SerializeToString,
            mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCPService/QueryLLM',
            mcp__pb2.QueryLLMRequest.SerializeToString,
            mcp__pb2.QueryLLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
