# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from docs.proto import mcp_pb2 as docs_dot_proto_dot_mcp__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in docs/proto/mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MCPStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveDocument = channel.unary_unary(
                '/mcp.MCP/SaveDocument',
                request_serializer=docs_dot_proto_dot_mcp__pb2.SaveDocReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.SaveDocResp.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/mcp.MCP/GetDocument',
                request_serializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.GetDocResp.FromString,
                _registered_method=True)
        self.QueryLLM = channel.unary_unary(
                '/mcp.MCP/QueryLLM',
                request_serializer=docs_dot_proto_dot_mcp__pb2.QueryLLMReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.QueryLLMResp.FromString,
                _registered_method=True)
        self.WriteMetric = channel.unary_unary(
                '/mcp.MCP/WriteMetric',
                request_serializer=docs_dot_proto_dot_mcp__pb2.WriteMetricReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.WriteAck.FromString,
                _registered_method=True)
        self.WriteAudit = channel.unary_unary(
                '/mcp.MCP/WriteAudit',
                request_serializer=docs_dot_proto_dot_mcp__pb2.WriteAuditReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.WriteAck.FromString,
                _registered_method=True)
        self.SaveOrchestration = channel.unary_unary(
                '/mcp.MCP/SaveOrchestration',
                request_serializer=docs_dot_proto_dot_mcp__pb2.OrchestrationState.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.WriteAck.FromString,
                _registered_method=True)
        self.GetOrchestration = channel.unary_unary(
                '/mcp.MCP/GetOrchestration',
                request_serializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.OrchestrationState.FromString,
                _registered_method=True)
        self.GetOcrOutput = channel.unary_unary(
                '/mcp.MCP/GetOcrOutput',
                request_serializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.OcrOutput.FromString,
                _registered_method=True)
        self.GetMappedSchema = channel.unary_unary(
                '/mcp.MCP/GetMappedSchema',
                request_serializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.MappedSchema.FromString,
                _registered_method=True)
        self.GetValidationLogs = channel.unary_unary(
                '/mcp.MCP/GetValidationLogs',
                request_serializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
                response_deserializer=docs_dot_proto_dot_mcp__pb2.ValidationLogs.FromString,
                _registered_method=True)


class MCPServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLLM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveOrchestration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrchestration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOcrOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMappedSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidationLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveDocument,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.SaveDocReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.SaveDocResp.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.GetDocResp.SerializeToString,
            ),
            'QueryLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLLM,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.QueryLLMReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.QueryLLMResp.SerializeToString,
            ),
            'WriteMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteMetric,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.WriteMetricReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.WriteAck.SerializeToString,
            ),
            'WriteAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteAudit,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.WriteAuditReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.WriteAck.SerializeToString,
            ),
            'SaveOrchestration': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveOrchestration,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.OrchestrationState.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.WriteAck.SerializeToString,
            ),
            'GetOrchestration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrchestration,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.OrchestrationState.SerializeToString,
            ),
            'GetOcrOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOcrOutput,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.OcrOutput.SerializeToString,
            ),
            'GetMappedSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMappedSchema,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.MappedSchema.SerializeToString,
            ),
            'GetValidationLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValidationLogs,
                    request_deserializer=docs_dot_proto_dot_mcp__pb2.GetDocReq.FromString,
                    response_serializer=docs_dot_proto_dot_mcp__pb2.ValidationLogs.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.MCP', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.MCP', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCP(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/SaveDocument',
            docs_dot_proto_dot_mcp__pb2.SaveDocReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.SaveDocResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/GetDocument',
            docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.GetDocResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/QueryLLM',
            docs_dot_proto_dot_mcp__pb2.QueryLLMReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.QueryLLMResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/WriteMetric',
            docs_dot_proto_dot_mcp__pb2.WriteMetricReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.WriteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/WriteAudit',
            docs_dot_proto_dot_mcp__pb2.WriteAuditReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.WriteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveOrchestration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/SaveOrchestration',
            docs_dot_proto_dot_mcp__pb2.OrchestrationState.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.WriteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrchestration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/GetOrchestration',
            docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.OrchestrationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOcrOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/GetOcrOutput',
            docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.OcrOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMappedSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/GetMappedSchema',
            docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.MappedSchema.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidationLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCP/GetValidationLogs',
            docs_dot_proto_dot_mcp__pb2.GetDocReq.SerializeToString,
            docs_dot_proto_dot_mcp__pb2.ValidationLogs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
