# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from docs.proto import agent_comm_pb2 as docs_dot_proto_dot_agent__comm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in docs/proto/agent_comm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentCommStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartOCR = channel.unary_unary(
                '/agent.AgentComm/StartOCR',
                request_serializer=docs_dot_proto_dot_agent__comm__pb2.OCRRequest.SerializeToString,
                response_deserializer=docs_dot_proto_dot_agent__comm__pb2.OCRResponse.FromString,
                _registered_method=True)
        self.MapSchema = channel.unary_unary(
                '/agent.AgentComm/MapSchema',
                request_serializer=docs_dot_proto_dot_agent__comm__pb2.MapRequest.SerializeToString,
                response_deserializer=docs_dot_proto_dot_agent__comm__pb2.MapResponse.FromString,
                _registered_method=True)
        self.ValidateSchema = channel.unary_unary(
                '/agent.AgentComm/ValidateSchema',
                request_serializer=docs_dot_proto_dot_agent__comm__pb2.ValidateRequest.SerializeToString,
                response_deserializer=docs_dot_proto_dot_agent__comm__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/agent.AgentComm/GenerateReport',
                request_serializer=docs_dot_proto_dot_agent__comm__pb2.ReportRequest.SerializeToString,
                response_deserializer=docs_dot_proto_dot_agent__comm__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.Convert = channel.unary_unary(
                '/agent.AgentComm/Convert',
                request_serializer=docs_dot_proto_dot_agent__comm__pb2.ConvertRequest.SerializeToString,
                response_deserializer=docs_dot_proto_dot_agent__comm__pb2.ConvertResponse.FromString,
                _registered_method=True)
        self.PushIntegration = channel.unary_unary(
                '/agent.AgentComm/PushIntegration',
                request_serializer=docs_dot_proto_dot_agent__comm__pb2.IntegrationRequest.SerializeToString,
                response_deserializer=docs_dot_proto_dot_agent__comm__pb2.IntegrationResponse.FromString,
                _registered_method=True)
        self.EventStream = channel.stream_stream(
                '/agent.AgentComm/EventStream',
                request_serializer=docs_dot_proto_dot_agent__comm__pb2.AgentEvent.SerializeToString,
                response_deserializer=docs_dot_proto_dot_agent__comm__pb2.AgentAck.FromString,
                _registered_method=True)


class AgentCommServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartOCR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Convert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventStream(self, request_iterator, context):
        """Optional event stream for A2A events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentCommServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartOCR': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOCR,
                    request_deserializer=docs_dot_proto_dot_agent__comm__pb2.OCRRequest.FromString,
                    response_serializer=docs_dot_proto_dot_agent__comm__pb2.OCRResponse.SerializeToString,
            ),
            'MapSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.MapSchema,
                    request_deserializer=docs_dot_proto_dot_agent__comm__pb2.MapRequest.FromString,
                    response_serializer=docs_dot_proto_dot_agent__comm__pb2.MapResponse.SerializeToString,
            ),
            'ValidateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSchema,
                    request_deserializer=docs_dot_proto_dot_agent__comm__pb2.ValidateRequest.FromString,
                    response_serializer=docs_dot_proto_dot_agent__comm__pb2.ValidateResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=docs_dot_proto_dot_agent__comm__pb2.ReportRequest.FromString,
                    response_serializer=docs_dot_proto_dot_agent__comm__pb2.ReportResponse.SerializeToString,
            ),
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=docs_dot_proto_dot_agent__comm__pb2.ConvertRequest.FromString,
                    response_serializer=docs_dot_proto_dot_agent__comm__pb2.ConvertResponse.SerializeToString,
            ),
            'PushIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.PushIntegration,
                    request_deserializer=docs_dot_proto_dot_agent__comm__pb2.IntegrationRequest.FromString,
                    response_serializer=docs_dot_proto_dot_agent__comm__pb2.IntegrationResponse.SerializeToString,
            ),
            'EventStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=docs_dot_proto_dot_agent__comm__pb2.AgentEvent.FromString,
                    response_serializer=docs_dot_proto_dot_agent__comm__pb2.AgentAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentComm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentComm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentComm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartOCR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentComm/StartOCR',
            docs_dot_proto_dot_agent__comm__pb2.OCRRequest.SerializeToString,
            docs_dot_proto_dot_agent__comm__pb2.OCRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MapSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentComm/MapSchema',
            docs_dot_proto_dot_agent__comm__pb2.MapRequest.SerializeToString,
            docs_dot_proto_dot_agent__comm__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentComm/ValidateSchema',
            docs_dot_proto_dot_agent__comm__pb2.ValidateRequest.SerializeToString,
            docs_dot_proto_dot_agent__comm__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentComm/GenerateReport',
            docs_dot_proto_dot_agent__comm__pb2.ReportRequest.SerializeToString,
            docs_dot_proto_dot_agent__comm__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentComm/Convert',
            docs_dot_proto_dot_agent__comm__pb2.ConvertRequest.SerializeToString,
            docs_dot_proto_dot_agent__comm__pb2.ConvertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentComm/PushIntegration',
            docs_dot_proto_dot_agent__comm__pb2.IntegrationRequest.SerializeToString,
            docs_dot_proto_dot_agent__comm__pb2.IntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agent.AgentComm/EventStream',
            docs_dot_proto_dot_agent__comm__pb2.AgentEvent.SerializeToString,
            docs_dot_proto_dot_agent__comm__pb2.AgentAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
